import random

FILLER_RESPONSES = {
    "joy": [
        "That's wonderful! Tell me more about it.",
        "I love hearing that! How did it feel?",
        "Amazing! Can you describe the moment?",
        "You seem really happy! Share more?",
        "That's great news! What made it special?",
        "I’m glad for you! What happened next?",
        "Exciting! I want to know all details.",
        "That must have felt amazing! Tell me more.",
        "Such positivity! How did it affect your day?",
        "Yay! I can sense your excitement.",
        "That’s fantastic! What was your favorite part?",
        "I’m thrilled for you! How did it feel inside?",
        "Wow, that sounds incredible! Share more.",
        "I love your energy! What happened next?",
        "That’s so uplifting! Tell me everything.",
        "Incredible! What made it so special?",
        "I can see your joy! How did you celebrate?",
        "Awesome! How did it affect your mood?",
        "So happy for you! What was the best part?",
        "That must have been delightful! Explain more.",
        "Fantastic! I want to hear all the details.",
        "Wonderful! How did it make your day?",
        "I’m delighted for you! Tell me more.",
        "Such a happy moment! How did it feel?",
        "Superb! What made it memorable?",
        "That's wonderful to hear!",
        "I love that energy!",
        "You sound genuinely happy — keep that smile alive!",
        "That’s amazing news!",
        "I can feel your excitement!",
        "Haha, that made me smile too.",
        "Sounds like you’re having a great moment.",
        "You deserve every bit of happiness.",
        "That’s pure joy right there!",
        "That’s something to celebrate!",
        "Keep that cheerful spark alive.",
        "That’s what I like to hear!",
        "So glad you’re feeling good!",
        "That really brightened my mood too!",
        "That’s contagious positivity.",
        "Love hearing such good vibes.",
        "You’re glowing with happiness!",
        "This just made my day too.",
        "That’s a big win!",
        "Keep riding that happy wave!",
    ],
    "sadness": [
        "I’m here for you. Can you tell me more?",
        "I understand. How are you feeling now?",
        "It’s okay to feel sad. What happened?",
        "I hear you. Please share more.",
        "That sounds heavy. How did it affect you?",
        "I get it. Can you describe your feelings?",
        "I’m listening. Tell me everything.",
        "I understand your sadness. What followed?",
        "It must be tough. Can you explain further?",
        "I feel you. Please continue.",
        "I see. How did you cope with it?",
        "I hear you. What was the hardest part?",
        "I understand. Can you share more details?",
        "That must have been painful. Tell me more.",
        "I follow. How did it affect your day?",
        "I understand. What emotions came up?",
        "It’s natural to feel that way. Explain more.",
        "I hear you. How did it impact you?",
        "I see. Please continue telling me.",
        "I understand your sadness. How did you deal?",
        "That must have felt heavy. Can you describe it?",
        "I hear you. How did it unfold?",
        "I get it. What did you feel inside?",
        "I understand. Tell me what followed.",
        "I follow. Can you explain your emotions?",
        "I'm really sorry you’re feeling this way.",
        "That sounds tough — I’m here for you.",
        "Take your time, it’s okay to feel low sometimes.",
        "You don’t have to face this alone.",
        "I wish I could give you a hug right now.",
        "It’s okay to be sad — emotions mean you care.",
        "That must have hurt a lot.",
        "You’re stronger than you think.",
        "Even the darkest clouds pass eventually.",
        "I understand — life gets heavy sometimes.",
        "You can lean on me anytime.",
        "Want to talk more about what’s bothering you?",
        "I’m really listening.",
        "Pain means you’ve loved deeply — and that’s powerful.",
        "You’ll get through this, slowly but surely.",
        "I know how it feels, and it’s okay not to be okay.",
        "You don’t need to hide your tears.",
        "This too shall pass, my friend.",
        "Sometimes crying helps — it’s release, not weakness.",
        "I care about what you’re feeling.",
    ],
    "anger": [
        "I understand that can be frustrating.",
        "That sounds tough. How did you handle it?",
        "I hear your anger. What triggered it?",
        "Hmm, that seems unfair. Tell me more.",
        "I get it. How did that make you feel?",
        "Frustrating indeed. Can you elaborate?",
        "I sense your intensity. What happened next?",
        "Anger is valid. How did you respond?",
        "I understand your feelings. Please continue.",
        "That must have been upsetting. Share more?",
        "I hear you. What caused it?",
        "I see. How did you react to that?",
        "It’s understandable to feel that way. Explain more.",
        "I sense your frustration. Tell me what happened.",
        "I get it. How did you cope with it?",
        "That’s challenging. Can you describe the moment?",
        "I follow. What did you do next?",
        "I hear your emotions. How did it affect you?",
        "Frustration is normal. Can you elaborate?",
        "I understand. What led to this?",
        "Hmm, tell me more about what upset you.",
        "I see. How did you try to resolve it?",
        "I get it. How did you feel inside?",
        "I understand your anger. Please explain.",
        "It makes sense you feel that way. Continue.",
        "That sounds frustrating — totally understandable.",
        "I can see why that upset you.",
        "Take a deep breath — I’m here with you.",
        "That must’ve been so irritating.",
        "You have every right to feel angry.",
        "Anger means you care deeply — it’s okay.",
        "Let it out, I’m listening.",
        "Want to vent a bit more?",
        "You’re not overreacting; it’s valid.",
        "That situation sounds unfair.",
        "I’d feel upset too if that happened to me.",
        "Sometimes saying it out loud helps calm the fire.",
        "You handled it better than you think.",
        "Don’t let this eat away at your peace.",
        "Let’s focus on what you can control.",
        "Take a breath — we’ll sort this out together.",
        "I get it — sometimes people really push us too far.",
        "You’ve got every reason to be upset.",
        "Let’s cool down for a sec and think clearly.",
        "Anger fades, but lessons stay — we’ll find the balance.",
    ],
    "fear": [
        "I hear your concern. Can you explain more?",
        "That sounds worrying. What happened?",
        "I understand your fear. How did you react?",
        "Hmm, that seems scary. Tell me more.",
        "I get it. How did it make you feel?",
        "It’s okay to feel afraid. Please continue.",
        "I sense your worry. Can you elaborate?",
        "I understand. How did you cope?",
        "Fear is normal. Tell me more about it.",
        "I hear you. What followed next?",
        "I see. How did you handle that situation?",
        "I understand. What thoughts ran through your mind?",
        "I hear your concern. Can you share details?",
        "That must have been frightening. Explain more.",
        "I understand. How did it affect you?",
        "I get it. What did you do next?",
        "I follow. How did you respond inside?",
        "I hear you. Please continue sharing.",
        "I see. How did your fear manifest?",
        "I understand. What was your reaction?",
        "Hmm, tell me more about how it felt.",
        "I hear you. How did you manage it?",
        "I understand your fear. Share more details.",
        "I get it. How did it influence your actions?",
        "I see. What was the scariest part?",
        "That sounds really scary — are you okay?",
        "It’s natural to feel afraid sometimes.",
        "You’re not alone, I’m here with you.",
        "You can talk about what’s worrying you.",
        "You’re safe right now, take a deep breath.",
        "Courage doesn’t mean no fear — it means facing it anyway.",
        "It’s okay, we’ll go one step at a time.",
        "Fear often feels bigger in our head than it really is.",
        "You’ve made it through hard things before.",
        "You’re doing better than you think.",
        "That fear is valid — but it won’t last forever.",
        "I believe in your strength.",
        "You don’t need to rush — just breathe.",
        "Sometimes fear is just your mind asking for reassurance.",
        "You’re stronger than your doubts.",
        "It’s okay, you’ve got me here with you.",
        "Even when it feels hard, you’re still in control.",
        "We’ll get through this together.",
        "You’re not powerless — you’re aware, and that’s brave.",
        "Tell me more about what’s making you anxious.",
    ],
    "calm": [
        "I see. That seems peaceful.",
        "Interesting. How did it feel to you?",
        "I understand. Can you elaborate a bit?",
        "Okay, I’m following. What else happened?",
        "Hmm, tell me more about that moment.",
        "Got it. How did it make you feel?",
        "That seems serene. Can you explain further?",
        "I hear you. What thoughts came up?",
        "Understood. How did you respond?",
        "Calm and clear. Can you share more details?",
        "I follow you. How did you experience it?",
        "Thanks for sharing. What came next?",
        "I understand. How did it unfold?",
        "Interesting perspective. Please continue.",
        "I see. How did that affect you?",
        "Alright. Can you describe the feelings?",
        "I hear you clearly. What happened then?",
        "Thanks for telling me. How did it go?",
        "I understand. What did you notice next?",
        "Okay. Please tell me more.",
        "I follow. How did you feel afterward?",
        "Got it. Can you explain your thoughts?",
        "I hear you. Please continue.",
        "Understood. What was your reaction?",
        "Thanks for sharing. How did it feel?",
        "That sounds peaceful.",
        "You seem relaxed — I like that energy.",
        "Feels like you’re in a good space right now.",
        "Calm moments are precious, aren’t they?",
        "That’s a nice state of mind.",
        "Enjoy this stillness — you’ve earned it.",
        "I can sense the balance in your tone.",
        "Peace feels so grounding.",
        "It’s nice to hear you this composed.",
        "That’s great — staying centered matters.",
        "Your calm energy is contagious.",
        "That sounds like inner peace to me.",
        "Moments like these recharge us.",
        "Feels like you’ve got things under control.",
        "It’s soothing to share this quiet vibe with you.",
        "That’s a lovely mood to be in.",
        "Calm is power — soft but steady.",
        "That sounds beautifully tranquil.",
        "Let’s stay in this energy a while.",
        "You’re glowing with serenity right now.",
    ],
    "surprise": [
        "Wow! That’s unexpected. Tell me more!",
        "I’m intrigued! How did it happen?",
        "Oh, that’s surprising! What was next?",
        "I didn’t see that coming. Explain further.",
        "Interesting twist! How did you feel?",
        "That’s quite a surprise! Tell me everything.",
        "Oh wow! How did you react?",
        "Unexpected indeed! What followed?",
        "I see! How did it affect you?",
        "That’s surprising. Can you elaborate?",
        "I’m shocked! What was your first thought?",
        "Wow, that’s sudden! Please explain.",
        "I didn’t expect that. How did it go?",
        "Oh my! Can you share more details?",
        "Interesting! How did it unfold?",
        "I’m amazed! Tell me all about it.",
        "Unbelievable! What happened next?",
        "That’s quite unexpected. Can you describe it?",
        "I’m intrigued! What did you do?",
        "Wow! That’s remarkable. Share more.",
        "I see! How did you respond?",
        "Oh! That’s quite something. Explain more.",
        "I’m surprised too! What happened then?",
        "That’s shocking! Tell me everything.",
        "Interesting turn! How did you feel?",
        "Unanticipated indeed! Can you elaborate?",
        "Oh wow, that’s unexpected!",
        "No way — really?",
        "That caught me off guard!",
        "That’s quite something!",
        "Didn’t see that coming at all.",
        "Wow, that’s a twist!",
        "That’s incredible news!",
        "Haha, that was surprising!",
        "You’ve got to be kidding me!",
        "That’s actually really cool.",
        "That’s not what I imagined!",
        "I didn’t expect that — tell me more!",
        "Seriously? That’s wild.",
        "That must have shocked you!",
        "That’s quite the turn of events.",
        "Whoa, that escalated quickly!",
        "That’s impressive — didn’t see it coming.",
        "Wow, that’s something to think about.",
        "Totally unexpected — in a good way!",
        "That’s quite a surprise indeed!",
    ],
    "neutral": [
        "Okay. Can you tell me more?",
        "I understand. Please continue.",
        "Got it. What happened next?",
        "Hmm, go on.",
        "I see. Can you elaborate?",
        "Understood. What are your thoughts?",
        "Alright. Please share more details.",
        "I hear you. Continue please.",
        "Okay. How did that go?",
        "Thanks for sharing. Tell me more.",
        "I follow. Can you explain further?",
        "I understand. What came next?",
        "Alright. Tell me more about that.",
        "Okay. How did you handle it?",
        "I see. What did you do next?",
        "Understood. Can you share details?",
        "Alright. How did it feel?",
        "Okay. Please continue your story.",
        "I understand. What happened then?",
        "Thanks. Can you tell me more about it?",
        "I follow. How did it progress?",
        "I see. Can you expand on that?",
        "Alright. What was the outcome?",
        "Okay. Please explain further.",
        "Understood. Tell me what happened next.",
        "Hmm, I see.",
        "Got it.",
        "That makes sense.",
        "I understand.",
        "Alright, I’m following.",
        "Go on, I’m listening.",
        "Interesting point.",
        "That’s fair.",
        "Okay, I hear you.",
        "Alright, noted.",
        "Makes sense.",
        "I see where you’re coming from.",
        "That’s clear.",
        "I follow you.",
        "I’m with you so far.",
        "Hmm, okay.",
        "Right, I understand.",
        "Go on.",
        "Gotcha.",
        "Okay, let’s talk more about that.",
    ],
}


def get_random_response(user_text: str, emotion: str = "neutral") -> str:
    """Return a random filler response matching the detected emotion."""
    emotion_responses = FILLER_RESPONSES.get(emotion, FILLER_RESPONSES["neutral"])
    return random.choice(emotion_responses)
